package paufregi.connectfeed.core.models

sealed class ActivityType(val matching: ActivityType?) {
    // Garmin
    data object Running : ActivityType(StravaRun)
    data object TrailRunning : ActivityType(StravaTrailRun)
    data object TreadmillRunning : ActivityType(StravaVirtualRun)
    data object Cycling : ActivityType("Cycling", 5, true)
    data object IndoorCycling : ActivityType("Indoor Cycling", 6, false)
    data object EBiking : ActivityType("eBiking", 7, true)
    data object Swimming : ActivityType("Swimming", 8, false)
    data object OpenWaterSwimming : ActivityType("Open Water Swimming", 9, false)
    data object Strength : ActivityType("Strength", 10, false)
    data object Walking : ActivityType("Walking", 11, true)
    data object Hiking : ActivityType("Hiking", 12, true)
    data object Rugby : ActivityType("Rugby", 13, false)
    data object Soccer : ActivityType("Soccer", 14, false)
    data object JumpRope : ActivityType("Jump Rope", 15, false)
    data object Breathwork : ActivityType("Breathwork", 16, false)
    data object Meditation : ActivityType("Meditation", 17, false)
    data object Yoga : ActivityType("Yoga", 18, false)
    data object Other : ActivityType("Other", 99, false)

    // Strava
    data object StravaAlpineSki: ActivityType(ProfileType.Other)
    data object StravaBackcountrySki: ActivityType(ProfileType.Other)
    data object StravaBadminton: ActivityType(ProfileType.Other)
    data object StravaCanoeing: ActivityType(ProfileType.Other)
    data object StravaCrossfit: ActivityType(ProfileType.Workout)
    data object StravaEBikeRide: ActivityType(ProfileType.Cycling)
    data object StravaElliptical: ActivityType(ProfileType.Workout)
    data object StravaEMountainBikeRide: ActivityType(ProfileType.Cycling)
    data object StravaGolf: ActivityType(ProfileType.Other)
    data object StravaGravelRide: ActivityType(ProfileType.Cycling)
    data object StravaHandcycle: ActivityType(ProfileType.Other)
    data object StravaHighIntensityIntervalTraining: ActivityType(ProfileType.Workout)
    data object StravaHike: ActivityType(ProfileType.Other)
    data object StravaIceSkate: ActivityType(ProfileType.Other)
    data object StravaKayaking: ActivityType(ProfileType.Other)
    data object StravaKitesurf: ActivityType(ProfileType.Other)
    data object StravaMountainBikeRide: ActivityType(ProfileType.Cycling)
    data object StravaNordicSki: ActivityType(ProfileType.Other)
    data object StravaPickleball: ActivityType(ProfileType.Other)
    data object StravaPilates: ActivityType(ProfileType.Workout)
    data object StravaRacquetball: ActivityType(ProfileType.Other)
    data object StravaRide: ActivityType(ProfileType.Cycling)
    data object StravaRockClimbing: ActivityType(ProfileType.Other)
    data object StravaRollerSki: ActivityType(ProfileType.Other)
    data object StravaRowing: ActivityType(ProfileType.Other)
    data object StravaRun: ActivityType(ProfileType.Running)
    data object StravaSail: ActivityType(ProfileType.Other)
    data object StravaSkateboard: ActivityType(ProfileType.Other)
    data object StravaSnowboard: ActivityType(ProfileType.Other)
    data object StravaSnowshoe: ActivityType(ProfileType.Other)
    data object StravaSoccer: ActivityType(ProfileType.Other)
    data object StravaSquash: ActivityType(ProfileType.Other)
    data object StravaStairStepper: ActivityType(ProfileType.Other)
    data object StravaStandUpPaddling: ActivityType(ProfileType.Other)
    data object StravaSurfing: ActivityType(ProfileType.Other)
    data object StravaSwim: ActivityType(ProfileType.Swimming)
    data object StravaTableTennis: ActivityType(ProfileType.Other)
    data object StravaTennis: ActivityType(ProfileType.Other)
    data object StravaTrailRun: ActivityType(ProfileType.Running)
    data object StravaVelomobile: ActivityType(ProfileType.Cycling)
    data object StravaVirtualRide: ActivityType(ProfileType.Cycling)
    data object StravaVirtualRow: ActivityType(ProfileType.Other)
    data object StravaVirtualRun: ActivityType(ProfileType.Running)
    data object StravaWalk: ActivityType(ProfileType.Other)
    data object StravaWeightTraining: ActivityType(ProfileType.Strength)
    data object StravaWheelchair: ActivityType(ProfileType.Other)
    data object StravaWindsurf: ActivityType(ProfileType.Other)
    data object StravaWorkout: ActivityType(ProfileType.Workout)
    data object StravaYoga: ActivityType(ProfileType.Workout)

    data object Unknown : ActivityType("Unknown", 100, false)
}
