package paufregi.connectfeed.presentation.ui.icons.garmin

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ConnectIcons.GravelCycling: ImageVector
    get() = image ?: ImageVector.Builder(
        name = "Connect.GravelCycling",
        defaultWidth = 522.dp,
        defaultHeight = 512.dp,
        viewportWidth = 522f,
        viewportHeight = 512f
    ).apply {
        path(fill = SolidColor(Color.Black)) {
            moveTo(295f, 119f)
            quadToRelative(-10f, -9f, -10f, -23f)
            quadToRelative(0f, -9f, 6f, -17.5f)
            reflectiveQuadToRelative(14.5f, -12f)
            reflectiveQuadToRelative(18.5f, -1.5f)
            reflectiveQuadToRelative(16.5f, 8.5f)
            reflectiveQuadToRelative(8.5f, 16.5f)
            reflectiveQuadToRelative(-1f, 19f)
            quadToRelative(-7f, 15f, -24f, 18.5f)
            reflectiveQuadToRelative(-29f, -8.5f)
            close()
            moveTo(465f, 385f)
            quadToRelative(14f, -24f, 13.5f, -51f)
            reflectiveQuadToRelative(-15.5f, -49.5f)
            reflectiveQuadToRelative(-40f, -32.5f)
            quadToRelative(-28f, -12f, -57.5f, -4f)
            reflectiveQuadToRelative(-48f, 31.5f)
            reflectiveQuadToRelative(-19f, 54f)
            reflectiveQuadToRelative(17f, 55f)
            reflectiveQuadToRelative(46.5f, 33.5f)
            reflectiveQuadToRelative(57.5f, -1.5f)
            reflectiveQuadToRelative(45.5f, -35.5f)
            close()
            moveTo(351f, 279f)
            quadToRelative(20f, -13f, 44.5f, -10.5f)
            reflectiveQuadToRelative(41.5f, 19.5f)
            reflectiveQuadToRelative(19.5f, 41f)
            reflectiveQuadToRelative(-11.5f, 44f)
            quadToRelative(-11f, 17f, -30f, 25f)
            reflectiveQuadToRelative(-39f, 4f)
            reflectiveQuadToRelative(-35f, -18.5f)
            reflectiveQuadToRelative(-19f, -34.5f)
            reflectiveQuadToRelative(4f, -39.5f)
            reflectiveQuadToRelative(25f, -30.5f)
            close()
            moveTo(277f, 183f)
            lineToRelative(34f, 34f)
            horizontalLineToRelative(91f)
            lineToRelative(-13f, -17f)
            lineToRelative(-59f, -10f)
            lineToRelative(-41f, -59f)
            lineToRelative(-35f, -15f)
            lineToRelative(-81f, 85f)
            quadToRelative(-4f, 4f, -3.5f, 9.5f)
            reflectiveQuadToRelative(4.5f, 8.5f)
            lineToRelative(81f, 56f)
            verticalLineToRelative(99f)
            horizontalLineToRelative(16f)
            lineToRelative(23f, -111f)
            lineToRelative(-50f, -48f)
            close()
            moveTo(143f, 245f)
            quadToRelative(18f, 0f, 34.5f, 7f)
            reflectiveQuadToRelative(29.5f, 19.5f)
            reflectiveQuadToRelative(20f, 29.5f)
            quadToRelative(9f, 22f, 5.5f, 46f)
            reflectiveQuadToRelative(-18f, 43.5f)
            reflectiveQuadToRelative(-36.5f, 28.5f)
            quadToRelative(-25f, 11f, -52.5f, 5.5f)
            reflectiveQuadToRelative(-46.5f, -25f)
            reflectiveQuadToRelative(-24.5f, -46.5f)
            reflectiveQuadToRelative(5f, -52f)
            reflectiveQuadToRelative(33.5f, -40.5f)
            reflectiveQuadToRelative(50f, -15.5f)
            close()
            moveTo(105f, 392f)
            quadToRelative(14f, 9f, 31.5f, 11f)
            reflectiveQuadToRelative(32.5f, -5f)
            quadToRelative(19f, -7f, 30.5f, -24.5f)
            reflectiveQuadToRelative(11.5f, -38f)
            reflectiveQuadToRelative(-11.5f, -37.5f)
            reflectiveQuadToRelative(-30.5f, -25f)
            reflectiveQuadToRelative(-39f, -4f)
            reflectiveQuadToRelative(-34.5f, 18.5f)
            reflectiveQuadToRelative(-18.5f, 34.5f)
            reflectiveQuadToRelative(4f, 39.5f)
            reflectiveQuadToRelative(24f, 30.5f)
            close()
            moveTo(241f, 456f)
            lineToRelative(-23f, -24f)
            lineToRelative(-23f, 24f)
            lineToRelative(23f, 23f)
            close()
            moveTo(147f, 432f)
            lineToRelative(23f, 24f)
            lineToRelative(-23f, 23f)
            lineToRelative(-23f, -23f)
            close()
            moveTo(318f, 456f)
            lineToRelative(-23f, -24f)
            lineToRelative(-23f, 24f)
            lineToRelative(23f, 23f)
            close()
            moveTo(366f, 432f)
            lineToRelative(23f, 24f)
            lineToRelative(-23f, 23f)
            lineToRelative(-23f, -23f)
            close()
        }
    }.build().also { image = it }

private var image: ImageVector? = null
