package paufregi.connectfeed.presentation.ui.icons.garmin

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ConnectIcons.TrackRunning: ImageVector
    get() = image ?: ImageVector.Builder(
        name = "Connect.TrackRunning",
        defaultWidth = 522.dp,
        defaultHeight = 512.dp,
        viewportWidth = 522f,
        viewportHeight = 512f
    ).apply {
        path(fill = SolidColor(Color.Black)) {
            moveTo(256f, 288f)
            lineToRelative(-33f, -32f)
            lineToRelative(-21f, 43f)
            lineToRelative(-86f, 55f)
            lineToRelative(11f, 14f)
            lineToRelative(9f, -5f)
            quadToRelative(12f, 15f, 29f, 23.5f)
            reflectiveQuadToRelative(37f, 8.5f)
            horizontalLineToRelative(38f)
            lineToRelative(9f, -22f)
            horizontalLineToRelative(-47f)
            quadToRelative(-27f, 0f, -46f, -20f)
            lineToRelative(67f, -33f)
            close()
            moveTo(195f, 246f)
            lineToRelative(16f, -22f)
            horizontalLineToRelative(-9f)
            quadToRelative(-35f, 0f, -60f, 25f)
            reflectiveQuadToRelative(-25f, 60f)
            quadToRelative(0f, 9f, 2f, 19f)
            lineToRelative(19f, -14f)
            verticalLineToRelative(-5f)
            quadToRelative(0f, -24f, 16.5f, -42.5f)
            reflectiveQuadToRelative(40.5f, -20.5f)
            close()
            moveTo(431f, 204f)
            lineToRelative(-17f, 14f)
            quadToRelative(21f, 17f, 32.5f, 40.5f)
            reflectiveQuadToRelative(11.5f, 50.5f)
            quadToRelative(0f, 32f, -16f, 59f)
            reflectiveQuadToRelative(-42.5f, 43f)
            reflectiveQuadToRelative(-58.5f, 16f)
            horizontalLineToRelative(-150f)
            quadToRelative(-32f, 0f, -58.5f, -16f)
            reflectiveQuadToRelative(-42.5f, -43f)
            reflectiveQuadToRelative(-16f, -59f)
            reflectiveQuadToRelative(16f, -58.5f)
            reflectiveQuadToRelative(42.5f, -42.5f)
            reflectiveQuadToRelative(58.5f, -16f)
            horizontalLineToRelative(43f)
            lineToRelative(14f, -21f)
            horizontalLineToRelative(-51f)
            lineToRelative(58f, -32f)
            lineToRelative(32f, 10f)
            lineToRelative(-49f, 73f)
            quadToRelative(-7f, 12f, 3f, 20f)
            lineToRelative(62f, 58f)
            lineToRelative(-46f, 108f)
            lineToRelative(17f, 8f)
            lineToRelative(14f, -21f)
            horizontalLineToRelative(42f)
            quadToRelative(35f, 0f, 60f, -25f)
            reflectiveQuadToRelative(25f, -60f)
            reflectiveQuadToRelative(-24f, -60f)
            reflectiveQuadToRelative(-59f, -26f)
            lineToRelative(17f, 24f)
            quadToRelative(20f, 7f, 32.5f, 23.5f)
            reflectiveQuadToRelative(12.5f, 37.5f)
            quadToRelative(0f, 27f, -19f, 45.5f)
            reflectiveQuadToRelative(-45f, 18.5f)
            horizontalLineToRelative(-28f)
            lineToRelative(49f, -74f)
            lineToRelative(-46f, -66f)
            lineToRelative(31f, -45f)
            lineToRelative(47f, 25f)
            lineToRelative(64f, -42f)
            lineToRelative(-10f, -11f)
            lineToRelative(-54f, 21f)
            lineToRelative(-64f, -64f)
            lineToRelative(-64f, -10f)
            lineToRelative(-74f, 56f)
            lineToRelative(7f, 8f)
            quadToRelative(-37f, 1f, -68f, 19.5f)
            reflectiveQuadToRelative(-49f, 50f)
            reflectiveQuadToRelative(-18f, 69f)
            reflectiveQuadToRelative(18.5f, 69.5f)
            reflectiveQuadToRelative(50.5f, 50.5f)
            reflectiveQuadToRelative(69f, 18.5f)
            horizontalLineToRelative(150f)
            quadToRelative(37f, 0f, 69f, -18.5f)
            reflectiveQuadToRelative(50.5f, -50.5f)
            reflectiveQuadToRelative(18.5f, -70f)
            quadToRelative(0f, -31f, -12.5f, -58f)
            reflectiveQuadToRelative(-35.5f, -47f)
            close()
            moveTo(378f, 128f)
            quadToRelative(15f, 0f, 26f, -11f)
            reflectiveQuadToRelative(11f, -26.5f)
            reflectiveQuadToRelative(-11f, -26.5f)
            reflectiveQuadToRelative(-26f, -11f)
            reflectiveQuadToRelative(-26f, 11f)
            reflectiveQuadToRelative(-11f, 26.5f)
            reflectiveQuadToRelative(11f, 26.5f)
            reflectiveQuadToRelative(26f, 11f)
            close()
        }
    }.build().also { image = it }

private var image: ImageVector? = null
